# LAYER: Base
FROM node:22-alpine AS base

# Enable Corepack to manage pnpm automatically
RUN corepack enable

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# LAYER: Builder copies the whole monorepo and prunes it
FROM base AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat
RUN pnpm install -g turbo

COPY . .
RUN turbo prune template-server --docker

# LAYER: Installer copies the pruned repo from the builder layer 
FROM base AS installer
WORKDIR /app
RUN apk add --no-cache libc6-compat

# First install dependencies (as they change less often)
COPY --from=builder /app/out/json/ ./
RUN pnpm install --frozen-lockfile

# Then add the rest and build
COPY --from=builder /app/out/full/ ./
RUN pnpm turbo build

# LAYER: Runner runs the built application from previous layers
FROM base AS runner
WORKDIR /app

COPY --from=installer /app .

CMD ["node", "apps/template-server/dist/src/app.js"]
