export const DASHBOARD_DUMMY_DATA = {
  brand: "OFSPACE.CO",
  user: {
    name: "Al Raihan",
    avatar: "/img/avatars/al.png",
    notifications: 3,
    messages: 26,
  },
  sidebarBadges: { message: 26, payment: 12 },
  summaries: {
    balance: {
      label: "Balance",
      value: 60900,
      changePct: 7.4,
    },
    spending: {
      label: "Spending",
      value: 1200,
      changePct: 3.4,
      periodLabel: "Last 12 Days",
      total: 355000,
      data: [
        { day: "Sun", amount: 21000 },
        { day: "Mon", amount: 32000 },
        { day: "Tue", amount: 18000 },
        { day: "Wed", amount: 47000 },
        { day: "Thu", amount: 23000 },
        { day: "Fri", amount: 35000 },
        { day: "Sat", amount: 27000 },
        { day: "Sun", amount: 15000 },
        { day: "Mon", amount: 39000 },
        { day: "Tue", amount: 30000 },
        { day: "Wed", amount: 42000 },
        { day: "Thu", amount: 26000 },
      ],
    },
    portfolio: {
      label: "Portfolio",
      value: 142390,
      changePct: 3.1,
    },
    investment: {
      label: "Investment",
      value: 32390,
      changePct: 11.4,
    },
  },

  spending: [
    {
      id: "tx_1001",
      title: "Shopping",
      subtitle: "West Mart Complex",
      amount: -1000,
      currency: "USD",
      direction: "debit",
      date: "2025-01-20",
      icon: "shopping-bag",
    },
    {
      id: "tx_1002",
      title: "Apple Payment",
      subtitle: "Payment Received",
      amount: 3000,
      currency: "USD",
      direction: "credit",
      date: "2025-01-21",
      icon: "apple",
    },
    {
      id: "tx_1003",
      title: "Paypal Payment",
      subtitle: "Payment Received",
      amount: 1000,
      currency: "USD",
      direction: "credit",
      date: "2025-01-21",
      icon: "paypal",
    },
    {
      id: "tx_1004",
      title: "Air Ticket",
      subtitle: "Emirates Airline",
      amount: -1210,
      currency: "USD",
      direction: "debit",
      date: "2025-01-22",
      icon: "plane",
    },
    {
      id: "tx_1005",
      title: "Credit Card Bill",
      subtitle: "Credit card payment",
      amount: -1000,
      currency: "USD",
      direction: "debit",
      date: "2025-01-22",
      icon: "credit-card",
    },
  ],
  spendingCategories: [
    {
      id: "bill_1",
      label: "Home Rent",
      note: "$2,200",
      amount: 2200,
      currency: "USD",
      icon: "home",
    },
  ],
  transactions: [
    {
      name: "Alice Johnson",
      status: "Active",
      date: "2025-08-20",
      amount: "1200$",
    },
    {
      name: "Brian Lee",
      status: "Pending Approval",
      date: "2025-08-18",
      amount: "850$",
    },
    {
      name: "Carla Mendes",
      status: "Inactive",
      date: "2025-08-15",
      amount: "0$",
    },
    {
      name: "David Kim",
      status: "Active",
      date: "2025-08-12",
      amount: "430$",
    },
    {
      name: "Emma Thompson",
      status: "Suspended",
      date: "2025-08-10",
      amount: "215$",
    },
  ],
};
